-- MySQL Script generated by MySQL Workbench

-- Mon Nov 14 17:09:48 2022

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------

-- Schema couture

-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `couture` ;

-- -------------------------------------vsc----------------

-- Schema couture

-- -----------------------------------------------------

/*CREATE SCHEMA IF NOT EXISTS `couture` DEFAULT CHARACTER SET utf8 ;
 USE `couture` ;
 -- -----------------------------------------------------
 -- Table `couture`.`Material`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`Material` (
 `id` INT NOT NULL AUTO_INCREMENT,
 `Cotton` VARCHAR(45) NULL,
 `Satin` VARCHAR(45) NULL,
 `Sythetic` VARCHAR(45) NULL,
 `Lin` VARCHAR(45) NULL,
 PRIMARY KEY (`id`)
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`Category`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`Category` (
 `id` INT NOT NULL,
 `Robes` VARCHAR(255) NULL,
 `Accessoires` VARCHAR(255) NULL,
 PRIMARY KEY (`id`)
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`Product`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`Product` (
 `id` INT NOT NULL AUTO_INCREMENT,
 `Title` VARCHAR(45) NOT NULL,
 `Image1` VARCHAR(45) NOT NULL,
 `Image2` VARCHAR(45) NOT NULL,
 `Price` DECIMAL(10, 2) NOT NULL,
 `Age` DECIMAL(2) NOT NULL,
 `Description` TEXT NOT NULL,
 `Material_id` INT NOT NULL,
 `Category_id` INT NOT NULL,
 `Color` TEXT NOT NULL,
 INDEX `Material_id_idx` (`Material_id` ASC) VISIBLE,
 INDEX `Category_id_idx` (`Category_id` ASC) VISIBLE,
 PRIMARY KEY (`id`),
 CONSTRAINT `FK_Material_id` FOREIGN KEY (`Material_id`) REFERENCES `couture`.`Material` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
 CONSTRAINT `FK_Category_id` FOREIGN KEY (`Category_id`) REFERENCES `couture`.`Category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`Rates`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`Rates` (
 `id` INT NOT NULL,
 `Note` INT NULL,
 PRIMARY KEY (`id`)
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`User`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`User` (
 `id` INT NOT NULL,
 `email` VARCHAR(45) NULL,
 `isAdmin` TINYINT(1) NULL,
 `FirstName` VARCHAR(45) NULL,
 `LastName` VARCHAR(45) NULL,
 `PostalCode` VARCHAR(45) NULL,
 `City` INT NULL,
 `Password word` VARCHAR(45) NULL,
 PRIMARY KEY (`id`)
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`Rate_Comment`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`Rate_Comment` (
 `id` INT NOT NULL,
 `Rate_id` INT NULL,
 `User_id` INT NULL,
 `Product_id` INT NULL,
 `Comment` TEXT(255) NULL,
 `isVisible` TINYINT(2) NULL,
 PRIMARY KEY (`id`),
 INDEX `Rate_id_idx` (`Rate_id` ASC) VISIBLE,
 INDEX `User_id_idx` (`User_id` ASC) VISIBLE,
 INDEX `Product_id_idx` (`Product_id` ASC) VISIBLE,
 CONSTRAINT `FK_Rate_id` FOREIGN KEY (`Rate_id`) REFERENCES `couture`.`Rates` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
 CONSTRAINT `FK_commentUser_id` FOREIGN KEY (`User_id`) REFERENCES `couture`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
 CONSTRAINT `FK_Product_id` FOREIGN KEY (`Product_id`) REFERENCES `couture`.`Product` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`payment`
 -- -----------------------------------------------------
 -- -----------------------------------------------------
 -- Table `couture`.`cart`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`cart` (
 `id` INT NOT NULL,
 `User_id` INT NOT NULL,
 `delivery_firstName` VARCHAR(45) NOT NULL,
 `delivery_lastName` VARCHAR(45) NOT NULL,
 `delivery_adress` VARCHAR(45) NOT NULL,
 `delivery_postalCode` INT NOT NULL,
 `delivery_city` VARCHAR(45) NOT NULL,
 `payment_type` INT NOT NULL,
 `status_id` INT NOT NULL,
 `delivery_price` INT NOT NULL,
 `total_price` INT NOT NULL,
 `date` DATE NOT NULL,
 PRIMARY KEY (`id`),
 INDEX `User_id_idx` (`User_id` ASC) VISIBLE,
 CONSTRAINT `FK_cartUser_id` FOREIGN KEY (`User_id`) REFERENCES `couture`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`many_product_cart`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`many_product_cart` (
 `id` INT NOT NULL,
 `cart_id` INT NOT NULL,
 `product_id` INT NOT NULL,
 PRIMARY KEY (`id`),
 INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
 INDEX `cart_id_idx` (`cart_id` ASC) VISIBLE,
 CONSTRAINT `FK_cart_id` FOREIGN KEY (`cart_id`) REFERENCES `couture`.`cart` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
 CONSTRAINT `FK_manyproduct_id` FOREIGN KEY (`product_id`) REFERENCES `couture`.`Product` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`Order`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`Order` (
 `id` INT NOT NULL,
 `User_id` INT NOT NULL,
 `delivery_firstName` VARCHAR(45) NOT NULL,
 `delivery_lastName` VARCHAR(45) NOT NULL,
 `delivery_adress` VARCHAR(45) NOT NULL,
 `delivery_postalCode` INT NOT NULL,
 `delivery_city` VARCHAR(45) NOT NULL,
 `payment_type` INT NOT NULL,
 `delivery_price` INT NOT NULL,
 `total_price` INT NOT NULL,
 `date` DATE NOT NULL,
 PRIMARY KEY (`id`),
 INDEX `User_id_idx` (`User_id` ASC) VISIBLE,
 CONSTRAINT `FK_User_id` FOREIGN KEY (`User_id`) REFERENCES `couture`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE = InnoDB;
 -- -----------------------------------------------------
 -- Table `couture`.`many_product_order`
 -- -----------------------------------------------------
 CREATE TABLE
 IF NOT EXISTS `couture`.`many_product_order` (
 `id` INT NOT NULL,
 `product_id` INT NOT NULL,
 `order_id` INT NOT NULL,
 PRIMARY KEY (`id`),
 INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
 INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
 CONSTRAINT `FK_manyorderproduct_id` FOREIGN KEY (`product_id`) REFERENCES `couture`.`Product` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
 CONSTRAINT `FK_order_id` FOREIGN KEY (`order_id`) REFERENCES `couture`.`Order` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE = InnoDB;
 USE `couture` ;*/